# -*- coding: utf-8 -*-
"""Setfit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13plgtCD-tn4ECIeT7k7yMKMq1uqLWL12
"""

!pip install setfit datasets

!pip install -U spacy
!python -m spacy download en_core_web_lg

from datasets import load_dataset
from setfit import AbsaTrainer, AbsaModel

train_dataset = load_dataset("tomaarsen/setfit-absa-semeval-restaurants", split="train[:128]")

train_dataset

!pip install -U spacy
!python -m spacy download en_core_web_lg

model = AbsaModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")

trainer = AbsaTrainer(model=model, train_dataset=train_dataset)

trainer.train()

model.save_pretrained(
    "drive/My Drive/setfit-absa-model-aspect",
    "drive/My Drive/setfit-absa-model-polarity"
)

from setfit import AbsaModel

preds = model.predict([
    "Best pizza outside of Italy and really tasty.",
    "It was a very bad product. Battery is not powerful."
])

preds

"""## Load the model"""

trained_model = AbsaModel.from_pretrained(
    "drive/My Drive/setfit-absa-model-aspect",
    "drive/My Drive/setfit-absa-model-polarity"
)

trained_model

"""## Push to Hub"""

!pip install huggingface_hub

from huggingface_hub import notebook_login

notebook_login()

model.push_to_hub()

